// Generated by nitro
import type { Serialize, Simplify } from "nitro/types";
declare module "nitro/types" {
  type Awaited<T> = T extends PromiseLike<infer U> ? Awaited<U> : T
  interface InternalApi {
    '/__nuxt_error': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../../node_modules/.pnpm/@nuxt+nitro-server-nightly@5.0.0-29569729.37112d05_@babel+core@7.29.0_chokidar@5.0.0_db_e8c6e6aca5408e6ec7c92f506e626c93/node_modules/@nuxt/nitro-server-nightly/dist/runtime/handlers/renderer').default>>>>
    }
    '/__nuxt_island/**': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../../#internal/nuxt/island-renderer').default>>>>
    }
  }
}
export {}